[build]
  base = "frontened"
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  REACT_APP_DASHBOARD_URL = "http://localhost:3001"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
