services:
  - type: web
    name: zerodha-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3002
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
